routes:
  -
    id: auth
    uri: /auth
    methods: ["POST"]
    plugins:
      proxy-rewrite:
        uri: "/realms/test-app/protocol/openid-connect/token"
        host: "auth-server:8080"
    upstream:
      nodes:
        "auth-server:8080": 1
      type: roundrobin
  -
    id: httpbin
    uri: /*
    upstream:
      nodes:
        "httpbin.org": 1
      type: roundrobin
    plugin_config_id: 1
  

plugin_configs:
  -
    id: 1
    plugins:
      openid-connect:
        client_id: "apisix"
        client_secret: "mWME2V9viaXoaTcqqbmXLizaxYaCSQH4"
        discovery: "http://auth-server:8080/realms/test-app/.well-known/openid-configuration"
        scope: "openid profile"
        bearer_only: true
        realm: "test-app"
    desc: "keycloak auth"
#END