routes:
  -
    id: httpbin
    uri: /*
    upstream:
      nodes:
        "httpbin.org": 1
      type: roundrobin
    plugin_config_id: 1

plugin_configs:
  -
    id: 1
    plugins:
      openid-connect:
        client_id: "apisix"
        client_secret: "mWME2V9viaXoaTcqqbmXLizaxYaCSQH4"
        discovery: "http://auth-server:8080/realms/test-app/.well-known/openid-configuration"
        scope: "openid profile"
        bearer_only: true
        realm: "test-app"
        redirect_uri: "http://apisix.local:9080/anything/callback"
        logout_path: "/anything/logout"
    desc: "keycloak auth"
#END