apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
  admin:
    allow_admin:               # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin                 # admin: manage all configuration data

      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer
    admin_listen:
      ip: 0.0.0.0                 # Specific IP, if not set, the default value is `0.0.0.0`.
      port: 9180 

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091